### PR TITLE
Update config arguments

### PR DESCRIPTION
**Pull request by awharn**
Replaces --user with --user-config (--uc) and --global with --global-config (--gc) due to problems that arise when trying to create a config through a session to a config service, such as the API Mediation Layer.

Thanks for the help @t1m0thyj

### CODE REVIEW

**Review by zFernand0 — COMMENTED** [review]
Code looks great.
Testing in a few minutes 😋

**Comment by t1m0thyj** [comment]
Normally I'm not sure if we care about changelog updates for PRs whose destination is the "next" branch. But since this is a breaking change in option names for some of the "zowe config" commands, should we document this in the changelog?

**Comment by zFernand0** [comment]
> Normally I'm not sure if we care about changelog updates for PRs whose destination is the "next" branch. But since this is a breaking change in option names for some of the "zowe config" commands, should we document this in the changelog?

It will only be considered a breaking change until next moves to zowe-v2-lts.
Then, it can be removed from the changelog (or at least omitted from the list of breaking changes), right?
😋

**Review by gejohnston — APPROVED** [review]
Looks good.

**Review by t1m0thyj — APPROVED** [review]
LGTM!

**Review by zFernand0 — APPROVED** [review]

**Pull request merged**
