### PR TITLE
Update Draft to Dec 2020

### LINKED ISSUE #624: IntelliSense not working in latest team profile schema
The IntelliSense doesn't seem to be working anymore with the latest version of team profiles schema. It appears to be related to the `dependentSchemas` field. 

image
If that field is removed, IntelliSense seems to work again.

image

### PR DESCRIPTION
**Pull request by zFernand0**
- Fix #624 
- Update draft + fix breaking changes between draft versions

### CODE REVIEW

**Comment by zFernand0** [comment]
Quirks:
- the profile type gets assumed depending on the first few properties that are specified
- the IntelliSense breaks on the properties block if you specify something that's not part of any profile definition

**Review by awharn — APPROVED** [review]

**Comment by zFernand0** [comment]
3250843 might help identify some of the changes needed to revert everything back to the april version in terms of additionalProperties and dependentSchemas.
Please feel free to force-push over this commit and remove it from the branch as it has broken tests. 😋

**Review by t1m0thyj — APPROVED** [review]
LGTM! Hiding whitespace changes made the diff much smaller 😛 

Verified that the v3 schema is fixed to show Intellisense on properties inside typed profiles. I'd appreciate if someone else can also test this - I don't trust my own testing after breaking the schema previously 😢

**Comment by zFernand0** [comment]
works for me, however profiles without a type are treated as zosmf profiles.
and out of the box we get squiggly lines on the first lpar1 profile properties. 
image

**Comment by zFernand0** [comment]
Still, way better than what it was before 😋

**Review by awharn — APPROVED** [review]

**Pull request merged**
