### PR TITLE
Update 'marked' to address security vulnerability

### PR DESCRIPTION
**Pull request by travatine**
There is a Denial of Service vulnerability in "marked" versions prior to 1.1.1,
the fix is available in 1.1.1 or later, see this commit which included the fix https://github.com/markedjs/marked/commit/bd4f8c464befad2b304d51e33e89e567326e62e0

This is the screenshot of "whitesource" which identified the issue:
image

In my package-lock.json, I also see:
```
"@zowe/imperative": {
			"version": "4.10.0",
			"resolved": "https://registry.npmjs.org/@zowe/imperative/-/imperative-4.10.0.tgz",
			"integrity": "sha512-P1/yKhg/pnQ/0anid2EYsFh2HES5fCL1VsJ5f43xU/IjPbvRW6dZAHdSQjrs20guWdJzTMFc8IULUzkxfWrCWg==",
			"requires": {
				"@types/lodash-deep": "2.0.0",
				"@types/yargs": "13.0.4",
				"@zowe/perf-timing": "1.0.7",
				"chalk": "2.4.2",
				"cli-table3": "0.5.1",
				"dataobject-parser": "1.2.1",
				"deepmerge": "3.0.0",
				"find-up": "2.1.0",
				"fs-extra": "8.1.0",
				"glob": "7.1.6",
				"js-yaml": "3.13.1",
				"jsonfile": "4.0.0",
				"jsonschema": "1.1.1",
				"levenshtein": "1.0.5",
				"lodash-deep": "2.0.0",
				"log4js": "6.3.0",
				"marked": "0.8.0",
				"moment": "2.20.1",
```

### CODE REVIEW

**Comment by zFernand0** [comment]
Thank you for opening the PR! : )
While all looks great, we may need a few more things for all checks to go green.
- DCO signoff
- Changelog update
- package-lock update

**Comment by travatine** [comment]
Hi @zFernand0 ,
I've done the DCO , Changelog and package lock updates.
Thanks

**Review by zFernand0 — APPROVED** [review]
LGTM!

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks for fixing vuln 🙂

Checked the [list of breaking changes](https://github.com/markedjs/marked/releases/tag/v1.0.0) in `marked@1.0.0` and it doesn't seem like we should be affected. 👍

**Pull request merged**
