### PR TITLE
Prevent truncation of last character of cookie element.

### PR DESCRIPTION
**Pull request by paulscott-psi**
REST API was failing to reuse the existing session. Discovered that the Cookie header contained a value that was truncated on the right by a single character. Removing the "- 1" in the substr() fixed the problem.

Signed-off-by: Paul Scott <paulscott@phoenixsoftware.com>

### CODE REVIEW

**Comment by zFernand0** [comment]
Hi @paulscott-psi,
Thanks a lot for opening this PR.
Could you create a very quick [issue](https://github.com/zowe/imperative/issues) for this?
Also, Would you mind updating the snapshots? 
These commands should do the trick: `npm run test:unit -- -u && npm run test:integration -- -u`
But if you don't want to wait for the entire suit to run, you can run the specific files:
`npx jest <filename> -u`

**Comment by paulscott-psi** [comment]
Opened issue #234

**Comment by paulscott-psi** [comment]
%npx jest AbstractSession.ts  -u
  Validation Error:

  Module jest-stare in the testResultsProcessor option was not found.
         <rootDir> is: /Users/pscott/Projects/paulscott-psi/imperative

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

**Comment by zFernand0** [comment]
> %npx jest AbstractSession.ts -u
> Validation Error:
> 
> Module jest-stare in the testResultsProcessor option was not found.
> <rootDir> is: /Users/pscott/Projects/paulscott-psi/imperative
> 
> Configuration Documentation:
> https://jestjs.io/docs/configuration.html

Do you have all the dependencies installed? `npm install` from the root directory of the project

**Comment by paulscott-psi** [comment]
%npm install
14704 error Unable to authenticate, need: Basic realm="Artifactory Realm"

**Comment by zFernand0** [comment]
> %npm install
> 14704 error Unable to authenticate, need: Basic realm="Artifactory Realm"

@paulscott-psi, This is due to the restricted access on today's artifactory.
This is something that will soon be addressed.
In the meantime, could you try this command?
- `npm install --@zowe:registry=https://registry.npmjs.org --no-package-lock --force`

**Comment by paulscott-psi** [comment]
Done. Here's the results.

%npm install --@zowe:registry=https://registry.npmjs.org --no-package-lock --force
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

> fsevents@1.2.9 install /Users/pscott/Projects/paulscott-psi/imperative/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/pscott/Projects/paulscott-psi/imperative/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> keytar@4.9.0 install /Users/pscott/Projects/paulscott-psi/imperative/node_modules/keytar
> prebuild-install || node-gyp rebuild


> node-pty@0.8.1 install /Users/pscott/Projects/paulscott-psi/imperative/node_modules/node-pty
> node scripts/install.js

  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:154:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  v8::String::Utf8Value file(info[0]->ToString());
                        ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:165:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value arg(argv_->Get(Nan::New<v8::Integer>(i))->ToString());
                          ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:176:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value pair(env_->Get(Nan::New<v8::Integer>(i))->ToString());
                          ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:181:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  v8::String::Utf8Value cwd_(info[3]->ToString());
                        ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:186:26: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  winp.ws_col = info[4]->IntegerValue();
                         ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:187:26: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  winp.ws_row = info[5]->IntegerValue();
                         ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:195:16: warning: 'ToBoolean' is deprecated [-Wdeprecated-declarations]
  if (info[8]->ToBoolean()->Value()) {
               ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2452:10: note: 'ToBoolean' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version",
         ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:230:22: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  int uid = info[6]->IntegerValue();
                     ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:231:22: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  int gid = info[7]->IntegerValue();
                     ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:315:26: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  winp.ws_col = info[0]->IntegerValue();
                         ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:316:26: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  winp.ws_row = info[1]->IntegerValue();
                         ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:360:21: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  int fd = info[0]->IntegerValue();
                    ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:363:26: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  winp.ws_col = info[1]->IntegerValue();
                         ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:364:26: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  winp.ws_row = info[2]->IntegerValue();
                         ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:387:21: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
  int fd = info[0]->IntegerValue();
                    ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:389:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  v8::String::Utf8Value tty_(info[1]->ToString());
                        ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/pscott/.node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/unix/pty.cc:489:21: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  Nan::Callback(cb).Call(Nan::GetCurrentContext()->Global(), 2, argv);
                    ^
../node_modules/nan/nan.h:1651:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../node_modules/nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
17 warnings generated.
  SOLINK_MODULE(target) Release/pty.node

> node-pty@0.8.1 postinstall /Users/pscott/Projects/paulscott-psi/imperative/node_modules/node-pty
> node scripts/post-install.js

added 1549 packages from 1363 contributors and audited 883694 packages in 39.751s
found 12 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by zFernand0** [comment]
Thanks for sharing the output.

> added 1549 packages from 1363 contributors and audited 883694 packages in 39.751s
> found 12 high severity vulnerabilities

This indicates that it at least was successful doing the installation. Now that you have all of the dev dependencies installed, you can build the source (`npm run build`) and then fix the snapshots with the commands I recommended before.

`npx jest <filename> -u` if you don't want to wait for the whole suit to run
`<filename>` is the name of the file that you noticed had an issue in the [pipeline](https://wash.zowe.org:8443/blue/organizations/jenkins/imperative/detail/PR-232/4/tests)

**Comment by paulscott-psi** [comment]
%npx jest AbstractSession.ts -u
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /Users/pscott/Projects/paulscott-psi/imperative
  3070 files checked.
  testMatch:  - 0 matches
  testPathIgnorePatterns: /node_modules/ - 3070 matches
  testRegex: __tests__.*\.(spec|test)\.ts$ - 139 matches
Pattern: AbstractSession.ts - 0 matches

**Comment by zFernand0** [comment]
Hey @paulscott-psi,
Would you mind running the following commands?
- `npm run test:unit -- -u`
- `npm run test:integration -- -u`

I may take a bit to run, but the `-u` option should fix the snapshot files.

**Comment by paulscott-psi** [comment]
The first command completed but with questionable results. 
The second command failed unable to delete cmd-cli. I moved it aside as recommended and the command failed again with:

%npm run test:integration -- -u

&gt; @zowe/imperative@4.1.8-alpha.201906141448 pretest:integration /Users/pscott/Projects/paulscott-psi/imperative
&gt; gulp test:installSampleClis

[08:56:13] Using gulpfile ~/Projects/paulscott-psi/imperative/gulpfile.js
[08:56:13] Starting 'test:installSampleClis'...
[08:56:13] Globally installing "cmd" cli...
[08:56:15] ***GLOBAL INSTALL "cmd" stderr:
npm ERR! path /Users/pscott/bin/node-v10.16.0-darwin-x64/lib/node_modules/cmd-sample-cli/lib/__tests__/__integration__/cmd/src/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/pscott/bin/node-v10.16.0-darwin-x64/lib/node_modules/cmd-sample-cli/lib/__tests__/__integration__/cmd/src/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pscott/.npm/_logs/2019-06-17T15_56_15_093Z-debug.log

[08:56:15] 'test:installSampleClis' errored after 1.67 s
[08:56:15] Error: Global install failed for "cmd" test CLI. Status code: "254". Please review the stdout/stderr for more details.
    at cliDirs.forEach (/Users/pscott/Projects/paulscott-psi/imperative/gulp/TestTasks.ts:269:18)
    at Array.forEach (&lt;anonymous&gt;)
    at installSampleClis (/Users/pscott/Projects/paulscott-psi/imperative/gulp/TestTasks.ts:257:13)
    at taskWrapper (/Users/pscott/Projects/paulscott-psi/imperative/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (/Users/pscott/Projects/paulscott-psi/imperative/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @zowe/imperative@4.1.8-alpha.201906141448 pretest:integration: `gulp test:installSampleClis`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @zowe/imperative@4.1.8-alpha.201906141448 pretest:integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pscott/.npm/_logs/2019-06-17T15_56_15_152Z-debug.log

**Comment by paulscott-psi** [comment]
I shouldn't try this stuff on an iPad. Accidentally closed the pull request when grabbing the screen to move the device. Ugh.

**Comment by paulscott-psi** [comment]
This doesn't seem worth the effort. I don't need credit for pull request. I'm happy that the fix gets implemented. Feel free to delete this pull request (delete 2 characters) and implement the change yourself. Unless this exercise is uncovering other problems you'd like to address, in which case I'm happy to go along with it.

**Comment by zFernand0** [comment]
Hey @paulscott-psi,
I'm really sorry you are having all these issues. I'm curious as to what is going on here.

- Are you running these tests on a Mac?
- Could you provide the output of `npm config get`? (feel free to remove any sensitive information)

**Comment by paulscott-psi** [comment]
Yes, running on macOS Mojave.

[config.txt](https://github.com/zowe/imperative/files/3302418/config.txt)

**Comment by paulscott-psi** [comment]
Basically same result when run in imperative directory:

%npm config get
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.9.0 node/v10.16.0 darwin x64"

; project config /Users/pscott/Projects/paulscott-psi/imperative/.npmrc
@zowe:registry = "https://gizaartifactory.jfrog.io/gizaartifactory/api/npm/npm-release/"

; userconfig /Users/pscott/.npmrc
@brightside:registry = "https://api.bintray.com/npm/ca/brightside"

; node bin location = /Users/pscott/bin/node-v10.16.0-darwin-x64/bin/node
; cwd = /Users/pscott/Projects/paulscott-psi/imperative
; HOME = /Users/pscott
; "npm config ls -l" to show all defaults.

**Comment by zFernand0** [comment]
Hey @paulscott-psi,
Thank you for providing the output of that command.
We will definitely look into what may be causing this, in order to do so, we will try to replicate the behavior on a Mac Mojave as well.
Apologies for the inconvenient.

**Comment by paulscott-psi** [comment]
Full disclosure (which should have been evident in the output posted earlier), I didn't install Node.js with the .pkg installer. I downloaded the binary distribution and plunked it into my ~/bin/ directory, set node, npm, and npm symbolic links to those executables in my PATH and set NODE_PATH environment variable suitably. I installed Node.js this way to get around access issues requiring root access when installing global packages. It all seems to work fine otherwise.

**Comment by tucker01** [comment]
Not sure if this will help your situation, but the npm folks recommend changing your global prefix (installing packages globally):

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

npm does some weird stuff... when running as root, they'll switch users during an install to prevent post install scripts from running with root permissions, etc.

**Comment by paulscott-psi** [comment]
Since I dropped Node.js into ~/bin/nodejs/ (subdirectory of home) and configured the appropriate NODE_PATH environment variable, global installs are done entirely inside my home directory structure. 

```
%npm install -g jshint
/Users/pscott/bin/node-v10.16.0/bin/jshint -> /Users/pscott/bin/node-v10.16.0/lib/node_modules/jshint/bin/jshint
+ jshint@2.10.2
added 30 packages from 15 contributors in 24.557s
```

As you can see there are no permission issues and everything is entirely inside my home directory structure, so I don't believe that suggestion is relevant here.

**Comment by tucker01** [comment]
The integration test task attempts to globally install some test CLIs (that are then later tested via shell scripts).

The error you are seeing seems to indicate that the test CLIs have not been built. Have you run `npm run build` on the project?

**Comment by paulscott-psi** [comment]
Yes, I ran npm run build as indicated in earlier post. I ran it again just now for good measure. It ended with these lines:

```
[11:02:54] Build for "imperative" cli completed successfully.
[11:02:54] Finished 'build:all-clis' after 18 s

> @zowe/imperative@4.1.8-alpha.201906141448 checkTestsCompile /Users/pscott/Projects/paulscott-psi/imperative
> echo "Checking that test source compiles" && tsc --noEmit -p tsconfig-tests.json

Checking that test source compiles
```

Then I ran npx jest AbstractSession.ts -u

```
%npx jest AbstractSession.ts -u
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /Users/pscott/Projects/paulscott-psi/imperative
  3088 files checked.
  testMatch:  - 0 matches
  testPathIgnorePatterns: /node_modules/ - 3088 matches
  testRegex: __tests__.*\.(spec|test)\.ts$ - 139 matches
Pattern: AbstractSession.ts - 0 matches
```

**Comment by paulscott-psi** [comment]
npm run build log attached.

[build.log](https://github.com/zowe/imperative/files/3336110/build.log)

**Comment by tucker01** [comment]
Sorry for the trouble. Thanks for helping us debug.

Since it looks like the test CLIs built correctly, you could try navigating to the projects `__tests__/__integration__/cmd` directory and issuing `npm install . -g`. This should install the test CLI globally. 

This would indicate we are not preserving your environment correctly when spawning `npm` from the `gulp` scripts.

**Comment by paulscott-psi** [comment]
```
%npm install . -g
/Users/pscott/bin/node-v10.16.0/bin/cmd-cli -> /Users/pscott/bin/node-v10.16.0/lib/node_modules/cmd-sample-cli/lib/__tests__/__integration__/cmd/src/index.js
+ cmd-sample-cli@0.0.0
updated 1 package in 1.88s

%npx jest AbstractSession.ts -u
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /Users/pscott/Projects/paulscott-psi/imperative
  3088 files checked.
  testMatch:  - 0 matches
  testPathIgnorePatterns: /node_modules/ - 3088 matches
  testRegex: __tests__.*\.(spec|test)\.ts$ - 139 matches
Pattern: AbstractSession.ts - 0 matches
```

**Comment by tucker01** [comment]
Thanks!

You mentioned creating symlinks. Does this explain the difference (one has `darwin-x64`) in the following:

Path from failure:
```
/Users/pscott/bin/node-v10.16.0-darwin-x64/lib/node_modules/cmd-sample-cli/lib/__tests__/__integration__/cmd/src/index.js
```

Path from successful global install:
```
/Users/pscott/bin/node-v10.16.0/lib/node_modules/cmd-sample-cli/lib/__tests__/__integration__/cmd/src/index.js
```

Also, I see there is no `prefix` set in the output of `npm config ls`. What does `npm config get prefix` show?

**Comment by paulscott-psi** [comment]
tucker01, those differences are because I shortened the name of the Node.js installation from node-v10.16.0-darwin-x64 to just node-v10.16.0. That change is not significant.

%npm config get prefix
/Users/pscott/bin/node-v10.16.0

Also, I just trashed the local repository and recloned it from GitHub then ran npm install . -g followed by "npx jest AbstractSession.ts -u" and I got this never before seen result:

```
● Validation Error:

  Module jest-stare in the testResultsProcessor option was not found.
         <rootDir> is: /Users/pscott/Projects/paulscott-psi/imperative

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

**Comment by tucker01** [comment]
If you removed everything, make sure to perform the following first:
1. `npm install --@zowe:registry=https://registry.npmjs.org --no-package-lock --force`
2. `npm run build`

Then try `npm run test`

**Comment by paulscott-psi** [comment]
I ran

```
npm install --@zowe:registry=https://registry.npmjs.org --no-package-lock --force
npm run build
```

Then I ran 

` npm run test:unit -- -u && npm run test:integration -- -u`

See attached log for results of this last command;

[test.log](https://github.com/zowe/imperative/files/3380453/test.log)

**Comment by tucker01** [comment]
Looks like you were able to get the sample CLIs globally installed, but now the scripts that run them are failing claiming they aren't able to be found. 

I'm going to move some of our discussion into a separate issue. Pete updated the snapshots and approved this PR.

**Comment by tucker01** [comment]
Moved to #252

**Pull request merged**
