### PR TITLE
Don't load token value into Session object if user or password are supplied

### LINKED ISSUE #413: Can't use service profile after storing token in base profile
Steps to Reproduce:
* Run the "auth login" command in Zowe CLI, and allow it to create a base profile with a token value stored in it.
* Create a service profile in Zowe CLI with user and password fields set.
* Run a CLI command and supply the name of your service profile as a CLI option.

The command fails with:
```
Command Error:
Expect Error: Required parameter 'tokenValue' must be undefined
```

### PR DESCRIPTION
**Pull request by tjohnsonBCM**
Fixes #413

### CODE REVIEW

**Comment by gejohnston** [comment]
Won't we also need a PR on the CLI to depend on the new version of imperative?

**Comment by tjohnsonBCM** [comment]
> Won't we also need a PR on the CLI to depend on the new version of imperative?

Yes, after this PR is merged and the new Imperative version is published to Zowe Artifactory, we'll need a PR for the CLI as well.

**Comment by zFernand0** [comment]
> > Won't we also need a PR on the CLI to depend on the new version of imperative?
> 
> Yes, after this PR is merged and the new Imperative version is published to Zowe Artifactory, we'll need a PR for the CLI as well.

if it's only to update the version number for imperative, then it should just work by re-running the pipeline after this one is merged in :yum:

We can open the PR for transparency though.

**Comment by zFernand0** [comment]
Changelog entry will still be required. so, a PR is needed.
Thanks @tjohnsonBCM for clarifying :yum:

**Pull request merged**
