### PR TITLE
adding appscan configure file into lts-incremental branch

### PR DESCRIPTION
**Pull request by raymondyanli**
Signed-off-by: Yan Li <raymondyanli@gmail.com>
@1000TurquoisePogs 
cc @jackjia-ibm
Adding AppScan configure file into lts-incremental branch to avoid coping it over from other location when runs lts-incremental branch.

### CODE REVIEW

**Comment by tucker01** [comment]
I've seen this come through before, maybe I'm out of the loop... but what is this and why is it necessary?

**Comment by raymondyanli** [comment]
Hi @zFernand0 we currently scan the codes for branch lts-incremental in CLI, but we don't have AppScan configure files under this branch, we have to workaround to get those configure files in oder to achieve security scan. so we'd like to have those configure files in its-incremental branch now.

**Comment by tucker01** [comment]
@raymondyanli who is performing these scans and for what purpose?

**Comment by raymondyanli** [comment]
@tucker01 Security source scan is one of the tasks in IBM Zowe automation pipeline, The scan will run once per week and it will generate vulnerability reports for developers to evaluate the potential security issues in the Zowe project.

**Comment by tucker01** [comment]
OK Thanks.

**Pull request merged**
