### PR TITLE
Export interfaces

### LINKED ISSUE #633: IConfigBuilderOpts not exported
https://github.com/zowe/imperative/blob/fd4120620c2488e9b29a61f830a94c1c22ac0250/packages/config/index.ts#L12-L27

### PR DESCRIPTION
**Pull request by zFernand0**
Fix #633

### CODE REVIEW

**Comment by zFernand0** [comment]
thanks @t1m0thyj and @awharn  for helping with this.
This PR may need to wait for a GHA fix on July 12th 😋 
Reference: https://github.com/actions/virtual-environments/issues/3861#issuecomment-894161602

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks for also fixing the vuln 🙂

**Review by awharn — APPROVED** [review]
LGTM! I think we can just ignore the MacOS build problems - this PR only exports interfaces, it shouldn't break anything.

**Review by gejohnston — COMMENTED** [review]
Looks good.

**Pull request merged**
