### PR TITLE
Enhance config command group

### PR DESCRIPTION
**Pull request by js665999**
- Add GET command 
- Add LIST command 
- refactor AppSettings.ts

### CODE REVIEW

**Comment by tucker01** [comment]
As the `imperative.json` file is updated/expanded with additional configuration items, how will the user know what is able to be set? It doesn't appear to mention the "set-able" values in the command definition?

**Comment by js665999** [comment]
> As the `imperative.json` file is updated/expanded with additional configuration items, how will the user know what is able to be set? It doesn't appear to mention the "set-able" values in the command definition?

List command is used to list all items which can be set

**Comment by tucker01** [comment]
How will users know to use `list` to see the "set-able" props and how will users know what values are valid for those props? 

Also, with the option name change, this cannot be ported to lts-incremental (breaking).

**Comment by jelaplan** [comment]
@BrandonJenkins14 Wrote
Hi, my only suggestion here is that if/when we add another override, we place a doc task to that story to add a new topic in the Configuration section of DocOps/Zowe doc. Something like "Using the Config Group" or "Setting Configuration Options", which can describe some of these complexities. 

Currently, the Secure Credential Plug-in doc explains how to set the CredentialManager value, which is probably sufficient right now.

**Comment by ChrisBoehmCA** [comment]
Thanks for updating based on feedback. Please resolve the merge conflicts

**Pull request merged**
