### PR TITLE
Fix/1.0.0/66

### LINKED ISSUE #66: A space in the path of your globally installed packages causes plugin validation to fail
A space in the path for you globally installed packages causes plugin validation to fail.

If an 'npm config get prefix' command returns a path with a space (like C:\Program Files\nodejs), then a command like 'zowe plugins install @brightside/ops@next' will fail with an error like the following:

```
Command failed: node <C:\Program Files\nodejs\node_modules\@brightside\core\lib\main.js> plugins validate @brightside/ops --response-format-json
internal/modules/cjs/loader.js:582
    throw err;
    ^
Error: Cannot find module 'C:\Program'
```

### PR DESCRIPTION
**Pull request by lyzla01**
Fix #66 issue where plugin validation failed when plugin path contain spaces.

### CODE REVIEW

**Comment by gejohnston** [comment]
We will postpone merging until an npm audit vulnerability is resolved.

**Comment by ChrisBoehmCA** [comment]
Merge conflict in package.json needs to be resolved

**Comment by lyzla01** [comment]
Merge conflict is resolved

**Comment by ChrisBoehmCA** [comment]
Please increase version to 1.0.6 after #80 is merged. Sorry for the inconvenience

**Pull request merged**
