### PR TITLE
Array with allowable values

### PR DESCRIPTION
**Pull request by liuxh0**
#428

### CODE REVIEW

**Comment by tjohnsonBCM** [comment]
LGTM. Please merge the latest changes from `master` into your branch.

**Comment by scifipony** [comment]
Please ensure in testing that an array of no elements (an option with no argument) is not flagged in error if **allowableValues** _is not coded_, or this will be a breaking change.

**Comment by liuxh0** [comment]
Hi @scifipony , I am not really sure what you mean.

The scenario you described will be flagged in error because an array is expected but a boolean is provided. The behavior is exactly the same before my change. Why this is a breaking change?

However in Zowe, an array-type option with no argument will result in an empty array instead of a boolean true. I am not familiar but I assume Zowe did some error handling.

**Comment by scifipony** [comment]
@liuxh0 

> in Zowe, an array-type option with no argument will result in an empty array instead of a boolean true.

Correct.

> I assume Zowe did some error handling

Best I can tell, it does not.  It certainly does not flag as in-error an array-type option with no argument.  I want to ensure that this behavior continues.  Should Zowe start flagging it, it would be a breaking change for my product.

**Comment by liuxh0** [comment]
@scifipony 
I am still a little bit confused. Before and after, the behavior is the same. How can I help here?

**Comment by scifipony** [comment]
> @scifipony
> I am still a little bit confused. Before and after, the behavior is the same. How can I help here?

All I was asking to _ensure the behavior didn't change_.  If the behavior is the same "before and after" the changes you made, then everything is fine.

**Pull request merged**
