### PR TITLE
Fix `--hw` not adding new lines

### LINKED ISSUE #715: zowe --hw is not honoring \n in description fields
Entering this into a cli plugin definition .
```
options: [
    {
      name: "chkInsourcelocation",
      aliases: ["csl"],
      description:
        "Check in Source File Location\n 1: Development Dataset\n 5: Package\n 7: Temporary Sequential Dataset\n D: Db2 Catalog (Stored procedure)\n E: Edit from Package Library\n B: Request Body ",
      type: "string",
      required: true,
      allowableValues: {
        values: ["1", "5", "7", "D", "E", "B"],
      },
      defaultValue: "B",
    }, 
```
is not being honoured in the zowe online web help
image

but is being dispalyed correctly when the cli command -h is displayed in the terminal output
image
i

### PR DESCRIPTION
**Pull request by zFernand0**
Fix #715

Before:
image

After:
image

### CODE REVIEW

**Review by gejohnston — APPROVED** [review]
Finally, an easy PR to read and review !!!

**Review by t1m0thyj — CHANGES_REQUESTED** [review]
I compared web help built from this branch, to web help built from master.

It seems that undesired new lines now get added to multi-line descriptions, forcing them to wrap with the same fixed width used in the CLI, instead of wrapping dynamically based on the width of a user's browser window.

For example (PR #716 on the left, master on the right):
image

**Comment by zFernand0** [comment]
After some discussion, it seems that we could disable wrapping in the `DefaultHelpGenerator` by adding/implementing a new optional property to the `IHelpGeneratorParms` interface and conditionally calling `TextUtils.wordWrap`

**Review by t1m0thyj — COMMENTED** [review]
Thanks for fixing the word wrap!

Could you please add a test in `packages\cmd\__tests__\help\WebHelpGenerator.test.ts` that verifies multi-line descriptions are indented and wrapped correctly?

**Comment by zFernand0** [comment]
Status:
- Added tests for double-spacing after binary name
- Added tests for wordWrap and intedentLines functions
- Moved TextUtils test file closer to its implementation
- Combined the `addChildAndDescendantsToSearch` functions into a private method
- Deprecated `flattenCommandTreeWithAliases(tree)` in favor of `flattenCommandTree(tree, true)`

**Review by t1m0thyj — APPROVED** [review]
LGTM! Thanks for also fixing the issue with extra space after CLI bin name in the web help! 🙂

**Review by awharn — APPROVED** [review]

**Pull request merged**
